### ISSUE TITLE
Window Sizing

### ISSUE THREAD

**Issue by chmoore889** [rndev2017/Ballz#13]
Window sizing is **constant** and **_cannot_** be played on anything besides your high res HP Spectre X360 and Dell XPS 13 displays.

**Comment by rndev2017** [comment]
haha sorry working on a fix

**Comment by chmoore889** [comment]
Recommendation to do based on window size like Breakout by Christopher Moore does

**Comment by mourchimpiri** [comment]
Ok first calm down. Second doesn't work on mine
